export const LOAD_POSTS = 'LOAD_POSTS'
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_ERROR = 'LOAD_POSTS_ERROR'

export const TOGGLE_BOOKED = 'TOGGLE_BOOKED'
export const REMOVE_POST = 'REMOVE_POST'
export const ADD_POST = 'ADD_POST'
